version: 2.1

#########
# Common
#########
orbs:
  heroku: circleci/heroku@1.0.1

############
# Workflows
############
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

##################
# Job Definitions
##################
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          command: |
            . venv/bin/activate
            python manage.py test

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '48:a0:87:54:ca:75:32:12:c6:9e:a2:77:a4:7a:08:a4'
      - heroku/install
      - heroku/deploy-via-git:
          force: true
